<?php

namespace sil24\VitrineBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopArticle($n=3) {
        return $this->getEntityManager()
                    ->createQuery('select a as art, sum(lc.quantite) as qte from sil24VitrineBundle:Article a, sil24VitrineBundle:LigneDeCommande lc where lc.article = a group by lc.article order by qte DESC')
                    ->setMaxResults($n)
                    ->getResult();
    }
}
