<?php

namespace sil24\VitrineBundle\Entity;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommandesForOneClient($client){
        return $this->getEntityManager()
                    ->createQuery('select cmd from sil24VitrineBundle:Commande cmd where cmd.client = :client')
                    ->setParameter('client',$client)
                    ->getResult();
    }
}
