sil24\VitrineBundle\Entity\Article:
  type: entity
  repositoryClass: sil24\VitrineBundle\Entity\ArticleRepository
  table: article
  id:
      id:
          type: integer
          generator: {strategy: AUTO}
  fields:
      nom:
          type: string
          length: 100
      prix:
          type: decimal
          scale: 2
      description:
          type: text
      stock:
          type: integer
  manyToOne:
      categorie:
          targetEntity: Categorie
          inversedBy: articles
          joinColumn:
              name: categorie_id
              referencedColumnName: id
  oneToMany:
      lignesDeCommande:
          targetEntity: LigneDeCommande
          mappedBy: article
  oneToOne:
      picture:
          targetEntity: Picture
          mappedBy: article
          joinColumn:
              name: picture_id
              referencedColumnName: id